-- ============================================================
-- Phase 6 — Returns Module + Void Sales
-- Run this manually in Supabase SQL Editor
-- ============================================================

-- ─── 1. return_number sequence (if not already created by DB trigger) ───────
-- If your `returns` table already has a trigger that auto-generates
-- `return_number`, skip this block.
CREATE SEQUENCE IF NOT EXISTS returns_number_seq START 1;

CREATE OR REPLACE FUNCTION generate_return_number()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.return_number IS NULL OR NEW.return_number = '' THEN
    NEW.return_number := 'RTN-' || TO_CHAR(NOW(), 'YYYYMMDD') || '-'
      || LPAD(NEXTVAL('returns_number_seq')::TEXT, 4, '0');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_generate_return_number ON returns;
CREATE TRIGGER trg_generate_return_number
  BEFORE INSERT ON returns
  FOR EACH ROW EXECUTE FUNCTION generate_return_number();

-- ─── 2. void_sale RPC ────────────────────────────────────────────────────────
-- Marks a sale as voided, restores stock batch quantities, writes audit log.
-- Caller must be authenticated; only admin/manager roles should reach this
-- (enforced via RLS / RoleRoute on the frontend).
CREATE OR REPLACE FUNCTION void_sale(
  p_sale_id UUID,
  p_reason  TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sale    sales%ROWTYPE;
  v_user_id UUID := auth.uid();
BEGIN
  -- Lock the row to prevent concurrent double-voids
  SELECT * INTO v_sale FROM sales WHERE id = p_sale_id FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Sale not found');
  END IF;

  IF v_sale.is_voided THEN
    RETURN jsonb_build_object('success', false, 'error', 'Sale is already voided');
  END IF;

  -- Mark as voided
  UPDATE sales
  SET
    is_voided   = TRUE,
    voided_by   = v_user_id,
    voided_at   = NOW(),
    void_reason = p_reason,
    updated_at  = NOW()
  WHERE id = p_sale_id;

  -- Restore stock: add sold quantities back to the batch referenced in each sale_item
  UPDATE stock_batches sb
  SET
    quantity_remaining = sb.quantity_remaining + si.quantity,
    updated_at         = NOW()
  FROM sale_items si
  WHERE si.sale_id = p_sale_id
    AND sb.id      = si.batch_id;

  -- Audit log
  INSERT INTO audit_logs (user_id, action, table_name, record_id, new_values)
  VALUES (
    v_user_id,
    'void_sale',
    'sales',
    p_sale_id,
    jsonb_build_object('reason', p_reason, 'voided_at', NOW())
  );

  RETURN jsonb_build_object('success', TRUE, 'sale_id', p_sale_id);

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', FALSE, 'error', SQLERRM);
END;
$$;

-- Grant execute to authenticated users (RLS / role check done in app layer)
GRANT EXECUTE ON FUNCTION void_sale(UUID, TEXT) TO authenticated;

-- ─── 3. process_return RPC ───────────────────────────────────────────────────
-- Creates a Return + ReturnItems, conditionally restocks batches, audits.
-- p_data shape:
-- {
--   "branch_id":     "uuid",
--   "sale_id":       "uuid",
--   "customer_id":   "uuid" | null,
--   "reason":        "text",
--   "return_type":   "restock" | "writeoff",
--   "refund_method": "cash" | "mtn_momo" | "airtel_money" | null,
--   "notes":         "text" | null,
--   "items": [
--     {
--       "sale_item_id":      "uuid",
--       "product_id":        "uuid",
--       "product_unit_id":   "uuid",
--       "batch_id":          "uuid" | null,
--       "quantity_returned": 2,
--       "refund_amount":     4000
--     }
--   ]
-- }
CREATE OR REPLACE FUNCTION process_return(
  p_data JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id      UUID    := auth.uid();
  v_branch_id    UUID    := (p_data->>'branch_id')::UUID;
  v_sale_id      UUID    := (p_data->>'sale_id')::UUID;
  v_customer_id  UUID    := NULLIF(p_data->>'customer_id', '')::UUID;
  v_return_type  TEXT    := p_data->>'return_type';
  v_refund_method TEXT   := NULLIF(p_data->>'refund_method', '');
  v_total_refund NUMERIC := 0;
  v_return_id    UUID;
  v_return_number TEXT;
  v_item         JSONB;
BEGIN
  -- Validate sale exists and is not voided
  IF NOT EXISTS (SELECT 1 FROM sales WHERE id = v_sale_id AND is_voided = FALSE) THEN
    RETURN jsonb_build_object('success', false, 'error', 'Sale not found or is already voided');
  END IF;

  -- Sum total refund from items
  SELECT COALESCE(SUM((item->>'refund_amount')::NUMERIC), 0)
  INTO v_total_refund
  FROM jsonb_array_elements(p_data->'items') item;

  -- Insert return header (return_number auto-generated by trigger)
  INSERT INTO returns (
    branch_id, sale_id, customer_id, processed_by,
    reason, return_type, status, total_refund,
    refund_method, notes
  ) VALUES (
    v_branch_id,
    v_sale_id,
    v_customer_id,
    v_user_id,
    p_data->>'reason',
    v_return_type::return_type,
    'completed'::return_status,
    v_total_refund,
    v_refund_method::payment_method,
    NULLIF(p_data->>'notes', '')
  )
  RETURNING id, return_number INTO v_return_id, v_return_number;

  -- Insert return items + conditionally restock
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_data->'items')
  LOOP
    INSERT INTO return_items (
      return_id, sale_item_id, product_id, product_unit_id,
      batch_id, quantity_returned, refund_amount, restocked
    ) VALUES (
      v_return_id,
      (v_item->>'sale_item_id')::UUID,
      (v_item->>'product_id')::UUID,
      (v_item->>'product_unit_id')::UUID,
      NULLIF(v_item->>'batch_id', '')::UUID,
      (v_item->>'quantity_returned')::INTEGER,
      (v_item->>'refund_amount')::NUMERIC,
      v_return_type = 'restock'
    );

    -- Restore stock batch if restocking
    IF v_return_type = 'restock' AND (v_item->>'batch_id') IS NOT NULL THEN
      UPDATE stock_batches
      SET
        quantity_remaining = quantity_remaining + (v_item->>'quantity_returned')::INTEGER,
        updated_at         = NOW()
      WHERE id = (v_item->>'batch_id')::UUID;
    END IF;
  END LOOP;

  -- Audit log
  INSERT INTO audit_logs (user_id, action, table_name, record_id, new_values)
  VALUES (
    v_user_id,
    'process_return',
    'returns',
    v_return_id,
    jsonb_build_object(
      'sale_id',       v_sale_id,
      'return_type',   v_return_type,
      'total_refund',  v_total_refund,
      'return_number', v_return_number
    )
  );

  RETURN jsonb_build_object(
    'success',       TRUE,
    'return_id',     v_return_id,
    'return_number', v_return_number,
    'total_refund',  v_total_refund
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', FALSE, 'error', SQLERRM);
END;
$$;

GRANT EXECUTE ON FUNCTION process_return(JSONB) TO authenticated;
